// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Proporciona las opciones de Firebase adecuadas según la plataforma en ejecución.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Configuración Firebase para la plataforma Web.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSBUsft86l9vuI81F9CB-VJQaSQo8Z2wk',
    appId: '1:840087008020:web:3afeb4ba2b624425438801',
    messagingSenderId: '840087008020',
    projectId: 'holamundo-f3029',
    authDomain: 'holamundo-f3029.firebaseapp.com',
    storageBucket: 'holamundo-f3029.firebasestorage.app',
    measurementId: 'G-F2GE916HT1',
  );

  // Configuración Firebase para Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsbKokNTwInheKTCUL8aJnf--c79XX8XQ',
    appId: '1:840087008020:android:0245b5f9cb039f8a438801',
    messagingSenderId: '840087008020',
    projectId: 'holamundo-f3029',
    storageBucket: 'holamundo-f3029.firebasestorage.app',
  );

  // Configuración Firebase para iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaU14e7Iy71lMaWMMB9TRjSVzdCuNcXCc',
    appId: '1:840087008020:ios:527cea3e996a05ac438801',
    messagingSenderId: '840087008020',
    projectId: 'holamundo-f3029',
    storageBucket: 'holamundo-f3029.firebasestorage.app',
    iosBundleId: 'com.example.holamundoFirebase',
  );
}
